// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260130194858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Apple Watch 7 ",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Apple Watch 8",
                            Price = 100000.0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Apple Watch 9",
                            Price = 30000.0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Apple Watch 10",
                            Price = 40000.0
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Apple Watch 11",
                            Price = 50000.0
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Apple Watch 12",
                            Price = 60000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
