// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260131165917_AddSliderTable")]
    partial class AddSliderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phone",
                            Url = "phone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics",
                            Url = "electronics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "White Goods",
                            Url = "white-goods"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Clothing",
                            Url = "clothing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cosmetics",
                            Url = "cosmetics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mother & Child",
                            Url = "mother-child"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Women",
                            Url = "Women"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Male",
                            Url = "Male"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Home & Living",
                            Url = "home-living"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Shoes & Bags",
                            Url = "shoes-bags"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "1.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Apple Watch 7 ",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "2.jpeg",
                            IsActive = false,
                            IsHome = true,
                            Name = "Apple Watch 8",
                            Price = 100000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "3.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Apple Watch 9",
                            Price = 30000.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "4.jpeg",
                            IsActive = false,
                            IsHome = false,
                            Name = "Apple Watch 10",
                            Price = 40000.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "5.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Apple Watch 11",
                            Price = 50000.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "6.jpeg",
                            IsActive = false,
                            IsHome = false,
                            Name = "Apple Watch 12",
                            Price = 60000.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "7.jpeg",
                            IsActive = false,
                            IsHome = false,
                            Name = "Apple Watch 13",
                            Price = 70000.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum at velit possimus aliquid, quisquam quam veniam corporis! Dolor, voluptas deleniti asperiores quibusdam iste in quod.",
                            Image = "8.jpeg",
                            IsActive = true,
                            IsHome = true,
                            Name = "Apple Watch 14",
                            Price = 80000.0
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Slider 1 Description",
                            Image = "slider-1.jpeg",
                            Index = 0,
                            IsActive = true,
                            Title = "Slider 1 Title"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Slider 2 Description",
                            Image = "slider-2.jpeg",
                            Index = 1,
                            IsActive = true,
                            Title = "Slider 2 Title"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Slider 3 Description",
                            Image = "slider-3.jpeg",
                            Index = 2,
                            IsActive = true,
                            Title = "Slider 3 Title"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.HasOne("dotnet_store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
